### ISSUE TITLE
UiView is dependent of the current selected "view as"-option on Storyboard

### ISSUE THREAD

**Issue by quiKsilverItaly** [dingwilson/SwiftVideoBackground#1]
So I noticed some weird behavior of the UiView, which includes the background video. It is dependent by the current selected "view as:" option on Storyboard (see this screenshot for illustration: http://www2.pic-upload.de/img/32461676/orientation.jpg ). If "iPhone 4" is selected for example, and the program is compiled and started on a iPhone 7 the background video appears to be too small (also AutoLayout of the UiView is set correctly like in the provided example). 

Did you know this is a thing? Is this on purpose? Thanks!

**Comment by quiKsilverItaly** [comment]
If I think about it, the background video does not adapt the Autolayout-settings. It just uses the currently generated width and height of the UiView dependent of the current "view as"-option.

**Comment by dingwilson** [comment]
Hey @quiKsilverItaly , thanks for giving SwiftVideoBackground a try! 👍

I have also run into this issue with a different project of mine (not related to SwiftVideoBackground) when using AutoLayout on a UIView (or UIView-based objects such as UIImageView). I don't think that the issue is with the background video, as it will fill the dimensions of the UIView. Rather, I think that autolayout is incorrectly setting the wrong constraints for the UIView, according to the size class selection you used (in your case, iPhone 4s). This seems to be due to the new size class options (and removal of Any,Any) in the interface builder in Xcode 8+.

A temporary solution is to select the proper phone version in the storyboard, as shown in the image you posted, and then building/running for that phone. (iPhone 4s -> iPhone 4s, or iPhone 7 -> iPhone 7).
