### ISSUE TITLE
weak' may only be applied to class and class-bound protocol types,... 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [dingwilson/SwiftVideoBackground#18]
I have noticed this error when I redownloaded my Xcode I don't know why this happened now

<img width="718" alt="untitled" src="https://user-images.githubusercontent.com/18103561/34374629-2abb5020-eaf3-11e7-9498-bff4150f7807.png">

**Comment by quanvo87** [comment]
If a `pod update` occurred, and your `SwiftVideoBackground` updated to 2.0, then you will need to use the new APIs. See our [migration guide](https://github.com/dingwilson/SwiftVideoBackground/blob/master/migration-2.0.0.md) for info (`SwiftVideoBackground` no longer subclasses `UIView`, it is it's own class).

If you want to continue using the older version, specify it in your `Podfile` and do another `pod update`:
```
pod 'SwiftVideoBackground', '~> 0.06'
```

Please let us know if you have any further trouble.

**Comment by AbdulazizAlmohsen** [comment]
problem solved !! Thanks

**Comment by dingwilson** [comment]
Hey @AbdulazizAlmohsen ! For anyone else who stumbles on this issue: I believe the issue here is that you are accidentally creating an instance of `SwiftVideoBackground`, instead of `BackgroundVideo`.  The correct code should have been:

```swift
@IBOutlet weak var backgroundVideo: BackgroundVideo!
```

Note that this only works before 2.0.0. For versions 2.0.0 and higher, please see the migration guide listed above.

I'm glad you figured out the issue!
