### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by quanvo87** [dingwilson/SwiftVideoBackground#19]
Playing with instruments shows a 16 kb leak. Going to investigate further. What I've observed:
- happens if video has sound
- responsible frame: `UISoundNewDevice`

Videos without sound don't appear to leak. Could also be a completely separate issue caused by something else in the app I was testing.

**Comment by dingwilson** [comment]
Are you testing this on a simulator or the actual device?

Sounds like an issue with AVAudioPlayer. There are several documented cases online of AVAudioPlayer leaking memory. This is an issue with Apple's framework, rather than our own. I'm not sure of the root cause, but apparently this issue should go away if you profile/run on an actual device.

If the issue is reproducible on an actual device, then we should probably look deeper into this.

**Comment by quanvo87** [comment]
Upon further testing I don't think my leak has to do with `SwiftVideoBackground`😀

**Comment by quanvo87** [comment]
I think what you said was the case--AVPlayer leaks on the simulator. On my device I wasn't seeing the leak.
