### ISSUE TITLE
Load video from assets catalog

### ISSUE THREAD

**Issue by perdona** [dingwilson/SwiftVideoBackground#22]
Only videos located at the project root can be played? What about videos that are included in xcassets?

**Comment by dingwilson** [comment]
Hey @perdona 

SwiftVideoBackground looks for the video in the app's bundle. This should include anything in the xcassets (although to be honest, I have never tried doing so). To check whether or not a video is part of the app's bundle, check your project's `Build Phases` section (as seen below).

<img width="559" alt="screenshot" src="https://user-images.githubusercontent.com/8827679/35995583-70cbaada-0cd9-11e8-9119-7d3c28bfddd5.png">

Hope that helps! Please let me know if you have any other questions. Thanks!

**Comment by perdona** [comment]
I tried to do so, and it doesn't find the video inside xcassets.

**Comment by perdona** [comment]
`BackgroundVideo: [ERROR] could not find video`
The video in question is included in xcassets, with the same name as before, when it was included inside root folder.

**Comment by dingwilson** [comment]
Hmm thats interesting.. After doing some more research, it seems that to access non-image files in a .xcassets file, you have to use [`NSDataAsset`](https://developer.apple.com/documentation/uikit/nsdataasset) to reference the file. The .xcassets are bundled together, and cannot be individually referenced using `Bundle.main`. 

Video retrieval using `NSDataAsset` is not currently supported by SwiftVideoBackground. This is something we will look into supporting in the future. (Contributions and pull requests are also encouraged.)

In the meantime, is there a specific reason why you're choosing to place the video in xcassets rather than separately bundled with the app?

**Comment by quanvo87** [comment]
What would it take to add this feature?

**Comment by perdona** [comment]
Shouldn't we use xcassets for this scenario?
What is the best practise to store a video that plays in bg of a view?
Also would love to contribute... I'll try to research that when I have some time. 
Thanks for the feedback!

**Comment by dingwilson** [comment]
@quanvo87 :

I actually wanted to see what you think would be best. Personally, I see three potential implementations:

1. Add some functionality to existing `play()` function to check for videos in both the bundle and the .xcassets. Play whichever video is found.
> I believe this would be the "cleanest" method from a user's perspective (still just one function they can call, no change to existing API), however I don't know if this is the "proper" way to do this. Also, how do we cover cases where filename is found in both the app's bundle AND .xcassets?

2. Overload `play()` function with two different sets of constructors. One for getting video from bundle, one from xcassets. (essentially two different `play()` functions)
> This might be the best option... However potentially confusing as we have multiple `play()` functions... we would have to document the differences for users, show them the options.

3. Completely change SwiftVideoBackground such that instead of passing in video filename, we have users pass in the reference to the video.
> While this is probably the cleanest from a code perspective, this adds difficulty to users, having to figure out how to add the video themselves.

**Comment by dingwilson** [comment]
@perdona :

I'm not exactly sure of the best practices for storing videos. Personally, I just individually bundle videos and audio files with my app.

From my understanding, while .xcassets can store any data (audio, video, images, etc.), they are most beneficial for images/icons due to being able to store/group 1x,2x,3x versions for different (retina) screen sizes. This does not translate into audio/video.

But again, I'm not particularly familiar with the best practices of storing videos.

**Comment by quanvo87** [comment]
From looking around, I'm not seeing a clear reason to put videos in xcassets. In addition, it seems like when I put a video into `xcassets`, its `mp4` type is lost, is it being stored as `NSData`? If that's the case you'd have to convert it to video then play. It seems like best practices is to put the video in the main bundle. Let us know what your research finds.

**Comment by dingwilson** [comment]
@perdona :

From what it seems like after reading @quanvo87 's input, I don't know if it is a good idea to support retrieval of videos from xcassets. We want this library to remain light/easy-to-use, and I think that adding this functionality will cause confusion without much gain. I will go ahead and close out this issue. If you disagree, please feel free to continue the discussion here, or create a new issue.

Thanks
-- Wilson

**Comment by quanvo87** [comment]
https://developer.apple.com/library/content/qa/qa1913/_index.html 🤔

**Comment by dingwilson** [comment]
Yeah it is definitely possible to store/retrieve other data files (incl. videos) from Asset Catalogs. The question is not whether we can, rather whether we should. What do you think?

**Comment by quanvo87** [comment]
Since these Apple docs are explaining how to do so, I think it's worth further investigation.

Also according to this [repo](https://github.com/saoudrizwan/Piano),
> Name of asset in any .xcassets catalogs. It's recommended to add your sound files to Asset Catalogs instead of as standalone files to your main bundle.

If this were true, it seems possible the same could also apply to videos.

**Comment by perdona** [comment]
Nice! I will try to collaborate anytime soon!

**Comment by quanvo87** [comment]
This person says you can't store videos in the asset catalogue and still use them, though doesn't explain why.

https://stackoverflow.com/questions/48767676/load-video-from-assets-xcassets?noredirect=1&lq=1

**Comment by dingwilson** [comment]
Closing for now - if there is interest, I can reopen again.
