### ISSUE TITLE
Open up properties like `isMuted` or `willLoopVideo` to be able to be changed at runtime

### ISSUE THREAD

**Issue by quanvo87** [dingwilson/SwiftVideoBackground#31]
also maybe rethink the name for `alpha`, to maybe `darkness` or something

**Comment by dingwilson** [comment]
Definitely agree with both.

1. One possible implementation might be having them as variables with a didSet() that checks if player is running, and updates the player or something?

2. Completely agree with the name change. Alpha is a terrible param name haha. Idk what I was thinking. `darkness` sounds... dark. I would say `brightness`, but then the 0 (lightest) to 1 (darkest) doesn't really make sense.. We could swap the 0 and 1, but then that would mess with existing users. Maybe darkness is the best name... Idk we can think about it.

These changes will most likely be breaking. We might want to figure out if there are any other big changes we want to make, since we'll have to move to release 3.0.0.

**Comment by quanvo87** [comment]
Yep I almost named this `3.0 Considerations`.
And yes `didSet()` magics was what I was thinking.
