### ISSUE TITLE
Dependency "SwiftVideoBackground" has no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by sjmueller** [dingwilson/SwiftVideoBackground#65]
When installing with carthage using `github "dingwilson/SwiftVideoBackground"` and then running:
```
carthage update --platform iOS
```
The process fails with: 
> Dependency "SwiftVideoBackground" has no shared framework schemes for any of the platforms: iOS

I tried with both carthage `0.28.0` and `0.29.0` with the same problem. Not sure what the issue is, but a [solution on stack overflow](https://stackoverflow.com/questions/35054788/carthage-no-shared-framework-schemes-for-ios-platform-for-my-own-framework) talks about needing the proper targets in `xcshareddata/xcschemes/.xcscheme`.

If you compare your single scheme to say Alamofire's https://github.com/Alamofire/Alamofire/tree/master/Alamofire.xcodeproj/xcshareddata/xcschemes maybe this provides a clue?

**Comment by dingwilson** [comment]
Hey @sjmueller ! Thanks for bringing this to our attention... Yes, I think the schemes for SwiftVideoBackground are not properly configured. I will look into this and fix it later this week when I get a chance. However, pull requests and contributions are highly encouraged as well, so please feel free to give it a try if you'd like. Thanks! 👍

**Comment by sjmueller** [comment]
Wish I was more experienced with preparing a lib for Carthage — if so, I would’ve already submitted a PR!

**Comment by natashaPolovnikova** [comment]
I have the same problem!

**Comment by dingwilson** [comment]
Hey @sjmueller @natashaPolovnikova 

Thanks for bringing this issue to my attention! This has now been fixed in PR #66, and is now live in master. 👍 Please try running `carthage update --platform iOS` again, and everything should work. I've tested it locally using a sample test project, and it seemed to work just fine, so I will go ahead and close this issue. If either of you run into any more issues, please feel free to create another issue and I will look into it.

Thanks for using SwiftVideoBackground! 👍
