### ISSUE TITLE
Bug, Video playing when app becomes  active even though i paused it 

### ISSUE THREAD

**Issue by korantengNanaYaw** [dingwilson/SwiftVideoBackground#72]
Why does a video automatically plays when my app applicationDidBecomeActive,but i paused the video when the applicationWillResignActive

``

**Comment by dingwilson** [comment]
Hey @korantengNanaYaw ! If I am understanding you correctly, you are asking why SwiftVideoBackground seems to resume the background video when `applicationDidBecomeActive` is called after the video was paused when `applicationWillResignActive` was called.

If so, this is the current expected behavior, implemented [here](https://github.com/dingwilson/SwiftVideoBackground/blob/master/SwiftVideoBackground/Sources/VideoBackground.swift#L52). This is so that the background video will always be playing when the view is active.

Closing issue as this is expected behavior. - if you believe this is not the case, please feel free to continue the conversation, and I will reopen this issue.

Thanks for using SwiftVideoBackground! 👍
