### ISSUE TITLE
Shared video background?

### ISSUE THREAD

**Issue by adrienblh** [dingwilson/SwiftVideoBackground#77]
Hi there, first of all thanks for this great framework, however to  display a video in a background on many UIViews without reloading or switch view?

**Comment by dingwilson** [comment]
Hi @adrienblh 

Thanks for trying out SwiftVideoBackground! 👍 I'm glad you like it.

In order to display a video on many UIViews in a single ViewController, I suggest instantiating multiple instances of VideoBackground and using one for each of your views. You can find an example of this [here](https://github.com/dingwilson/SwiftVideoBackground/blob/master/SwiftVideoBackground/MoreViewController.swift).

Please feel free to let me know if you have any other questions.

Thanks again!
Wilson

**Comment by adrienblh** [comment]
Hi there thank you for your answer! 
I was thinking about this kind of login / signup flow : 
One video in the background of many Uiviews without reloading the video and without showing the transition?

Thank you so much for taking the time!







Cordialement,


DIRECTION ARTISTIQUE | PARALLEL 
ADRIEN BELAICH

M +33(0)665 463 137 | +44(0) 7397 131298
WWW.PARALLELMAGAZINE.CO.UK

**Comment by dingwilson** [comment]
Yes that is definitely possible. In that case, I would recommend keeping the single instance of `VideoBackground`, and instead just modifying which uiviews are hidden/present, depending on which state it is in (login vs signup vs ...). This allows you to avoid the transitions between views.

**Comment by adrienblh** [comment]
You are very kind to take time to answer me! 
Thank you so much! I am having 3 UIViews (login, sign up, forget password) how would the code you talked about look like? How to hide/present transitions between the view? I am very sorry, I am a real beginner, thank you so much for your help and for sharing your knowledge!

Cordialement,


DIRECTION ARTISTIQUE | PARALLEL 
ADRIEN BELAICH

M +33(0)665 463 137 | +44(0) 7397 131298
WWW.PARALLELMAGAZINE.CO.UK
